name: Rust
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    name: Clippy
    runs-on: arc-runner-set-luna-guard
    container: ${{ vars.RUNNER_IMAGE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clippy
        run: cargo clippy
  harbor-ligthouse-image:
    name: Build lighthouse image
    runs-on: arc-runner-set
    container: ${{ vars.RUNNER_IMAGE_URL }}
    needs: [clippy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull QEMU image manually
        run: docker pull tonistiigi/binfmt:latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: harbor.home.local
          username: ${{ secrets.HARBOR_USER}}
          password: ${{ secrets.HARBOR_TOKEN}}
      - name: Build Image
        run: "docker build -t harbor.home.local/library/luna_guard:latest .\ndocker push harbor.home.local/library/luna_guard:latest \n"
        working-directory: lighthouse
  harbor-ligthouse-image-push:
    if: github.event_name == 'push'
    name: Push lighthouse image
    runs-on: arc-runner-set
    container: ${{ vars.RUNNER_IMAGE_URL }}
    needs: [harbor-ligthouse-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull QEMU image manually
        run: docker pull tonistiigi/binfmt:latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: harbor.home.local
          username: ${{ secrets.HARBOR_USER}}
          password: ${{ secrets.HARBOR_TOKEN}}
      - name: Build Image
        run: docker build -t harbor.home.local/library/luna_guard:latest .
        working-directory: lighthouse
      - name: Push Image
        run: docker push harbor.home.local/library/luna_guard:latest
        working-directory: lighthouse
